# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WARMGIS_Tools
                                 A QGIS plugin
 Water Management Tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-12
        copyright            : (C) 2022 by Rafael Kayser
        email                : rafael.hbkayser@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WARMGIS_Tools class from file WARMGIS_Tools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .WARMGIS_Tools import WARMGIS_Tools
    return WARMGIS_Tools(iface)
